import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstname: "Yuvraj",
    lastname: "Thapa",
    username: "yuvrajthapa",
    password: "yuvraj123",
    bio: "Speak truth, feel love, be free.",
    avatarUrl: "",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "Adarsh",
    lastname: "Negi",
    username: "adarshnegi",
    password: "adarsh123",
    bio: "Aspiring Enginneer",
    avatarUrl: "",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "Shaswat",
    lastname: "Gusain",
    username: "shaswatgusain",
    password: "shaswat123",
    bio: "Aspiring Enginneer",
    avatarUrl: "",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "Vinay",
    lastname: "Chand Ramola",
    username: "vinaychandramola",
    password: "vinay123",
    bio: "Aspiring Enginneer",
    avatarUrl: "",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "John",
    lastname: "Joe",
    username: "JohnJoe",
    password: "Joe1234",
    bio: "Margeting and Sales Enginneer",
    website: "https://margeting/sales/name.com",
    avatarUrl:
      "https://res.cloudinary.com/dgoldjr3g/image/upload/v1686804933/NegProjects/SocialMedia/62_qogeol.jpg",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "Stacy",
    lastname: "Lane",
    username: "Lane34",
    password: "abbc1234",
    bio: "Operation Enginneer",
    website: "https://google/pic/name.com",
    avatarUrl:
      "https://res.cloudinary.com/dgoldjr3g/image/upload/v1686804933/NegProjects/SocialMedia/10_yrt7lk.jpg",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstname: "Mario",
    lastname: "Chavez",
    username: "Chavez24",
    password: "Chavez12",
    bio: "Let's get to work",
    website: "https://google/pic/name.com",
    avatarUrl:
      "https://res.cloudinary.com/dgoldjr3g/image/upload/v1686804933/NegProjects/SocialMedia/11_zmzmjz.jpg",
    bookmarks: [],
    followers: [],
    following: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];